### ISSUE TITLE
Please update to 1.4.0

### ISSUE THREAD

**Issue by spallas** [ohueter/homebrew-tap#1]
https://github.com/ohueter/autokbisw/releases/tag/1.4.0

Thanks for the mouse fix.

**Comment by ohueter** [comment]
Hi @spallas, thanks for the kind words, let's forward this to @ryanmccardle who contributed the fix :-)

And thanks for posting, I wasn't aware Issues were disabled on the [autokbisw](https://github.com/ohueter/autokbisw) repo. Fixed that, and closing here!
