### ISSUE TITLE
Installation error: `xcrun: error: unable to lookup item 'PlatformPath'`

### ISSUE THREAD

**Issue by ggdupont** [ohueter/homebrew-tap#5]
I was not able to install the `ohueter/tap/autokbisw` package from brew today (I did so years ago on my previous machine).

The complete error is not clear to me:
```
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```

Doing the install on macos ventura 13.4.1 after a fresh reinstall of xcode. Am I missing some xcode plugins?

**Comment by ohueter** [comment]
Hi @ggdupont, are the Xcode command line tools installed on your system? Does following the steps at the end of this comment fix the issue: https://github.com/ohueter/autokbisw/issues/12#issuecomment-1282111860 ?

**Comment by ggdupont** [comment]
Thanks for the prompt reply!

Xcode command line tools is installed but with version 14.3.1xxx
```
$> pkgutil --pkg-info=com.apple.pkg.CLTools_Executables 
package-id: com.apple.pkg.CLTools_Executables
version: 14.3.1.0.1.1683849156
volume: /
location: /
install-time: 1686499315
```

Trying to rebuild from source gave me the same error.

```
$> swift build -c release --disable-sandbox --disable-dependency-cache
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```

Should I look for older version of Xcode command line tools? (I don't have an Apple dev account, not sure where I could get it)

**Comment by ohueter** [comment]
Please look at the steps in the accepted answer here and see if this fixes the errors you are encountering: https://stackoverflow.com/questions/43418533/running-swift-build-in-terminal-leading-to-platform-path-errors

**Comment by ggdupont** [comment]
This fixed it!
A simple path error... sorry I haven't thought about this (pretty acustomed to path errors in python and JAVA, should have spotted that too).

**Comment by ggdupont** [comment]
This fixed it!
A simple path error... sorry I haven't thought about this (pretty acustomed to path errors in python and JAVA, should have spotted that too).

**Comment by ohueter** [comment]
Awesome, glad it worked 🙌
